apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      project: capstone_app
  template:
    metadata:
      name: capstone_app
      labels:
        project: capstone_app
    spec:
      containers:
        - name: capstone
          image: 724012784310.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
          resources:
            requests:
              memory: 200Mi
              cpu: "0.25"
            limits:
              memory: "1Gi"
              cpu: "1"
      tolerations:
        - key: capstone
          operator: Equal
          value: "true"
          effect: NoSchedule
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: capstone-app-autoscaler
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: capstone-app
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app-service
  namespace: demo
spec:
  type: LoadBalancer
  selector:
    project: capstone_app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
